version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/tests/e2e/cookie-lab"
      - "/tests/e2e/runner"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker-compose"
    directory: "/tests/e2e"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/tests/e2e/cookie-lab"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "npm"
    directory: "/tests/e2e/runner"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "javascript"
