name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - lint-python
          - lint-javascript
          - lint-json
          - lint-yaml
          - lint-toml
          - lint-docker
          - lint-markdown
          - lint-actions
          - lint-html
          - lint-nginx
          - lint-compose

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          persist-credentials: false

      - name: Run ${{ matrix.target }}
        run: make ${{ matrix.target }}
